[package]
name = "hazelcast-rust-client"
version = "0.1.0"
authors = ["Grzegorz Gierlach <gierlachg@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.3"
futures = "0.3.1"
tokio = { version = "0.2.9", features = ["full"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
