[package]
name = "hazelcast-rust-client-macros"
version = "0.1.0"
authors = ["Grzegorz Gierlach <gierlachg@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0.7"
syn = { version = "1.0.13", features = ["full"] }
